CREATE TABLE IF NOT EXISTS content (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS subscriber (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

INSERT INTO content (title, url, type, published_at) VALUES
    ('Spring Modulith en Produccion: Lecciones Reales', 'https://blog.devnexus.io/spring-modulith-produccion', 'ARTICLE', '2026-01-10T09:15:00Z'),
    ('Patrones para Eventos de Dominio con Spring', 'https://engineering.codestack.io/eventos-dominio-spring', 'ARTICLE', '2026-01-12T14:40:00Z'),
    ('Construyendo APIs REST con Spring Boot 4', 'https://academy.byteforge.dev/cursos/spring-boot-4-rest', 'COURSE', '2026-01-15T11:30:00Z'),
    ('Arquitectura Hexagonal en Java Moderna', 'https://podcast.javahoy.fm/episodios/84', 'PODCAST', '2026-01-18T18:00:00Z'),
    ('Observabilidad con OpenTelemetry y Spring', 'https://videos.cloudnative.es/otel-spring-observabilidad', 'VIDEO', '2026-01-21T16:20:00Z'),
    ('Manejo de Transacciones sin Sorpresas', 'https://blog.cleancode.lat/transacciones-spring-guia', 'ARTICLE', '2026-01-24T08:05:00Z'),
    ('Introduccion a Spring Data JDBC', 'https://academy.byteforge.dev/cursos/spring-data-jdbc-intro', 'COURSE', '2026-01-26T13:10:00Z'),
    ('Escalando Jobs con Spring Batch', 'https://videos.cloudnative.es/spring-batch-escalado', 'VIDEO', '2026-01-29T10:45:00Z'),
    ('Testing de Integracion con Testcontainers', 'https://blog.devnexus.io/testcontainers-integracion', 'ARTICLE', '2026-02-02T12:00:00Z'),
    ('Diseño de APIs Versionadas: Buenas Practicas', 'https://podcast.javahoy.fm/episodios/87', 'PODCAST', '2026-02-05T17:15:00Z'),
    ('Seguridad JWT con Spring Security 7', 'https://academy.byteforge.dev/cursos/jwt-spring-security-7', 'COURSE', '2026-02-08T09:50:00Z'),
    ('Caching Inteligente con Redis', 'https://blog.cleancode.lat/caching-redis-spring', 'ARTICLE', '2026-02-11T15:25:00Z'),
    ('Mensajeria Asincrona con RabbitMQ', 'https://videos.cloudnative.es/rabbitmq-spring-async', 'VIDEO', '2026-02-14T11:05:00Z'),
    ('Refactorizando Monolitos a Moduliths', 'https://blog.devnexus.io/monolito-a-modulith', 'ARTICLE', '2026-02-17T19:40:00Z'),
    ('Spring AI para Equipos Backend', 'https://academy.byteforge.dev/cursos/spring-ai-backend', 'COURSE', '2026-02-20T07:35:00Z'),
    ('Guia de Migracion a Java 26', 'https://blog.cleancode.lat/migracion-java-26', 'ARTICLE', '2026-02-23T14:00:00Z'),
    ('Feature Flags y Despliegues Seguros', 'https://videos.cloudnative.es/feature-flags-despliegues', 'VIDEO', '2026-02-27T10:10:00Z'),
    ('Modelado de Agregados en DDD', 'https://podcast.javahoy.fm/episodios/90', 'PODCAST', '2026-03-02T20:30:00Z'),
    ('CQRS Practico con Spring', 'https://academy.byteforge.dev/cursos/cqrs-practico-spring', 'COURSE', '2026-03-05T09:05:00Z'),
    ('Resiliencia con Circuit Breakers', 'https://blog.devnexus.io/resiliencia-circuit-breaker', 'ARTICLE', '2026-03-08T13:45:00Z'),
    ('Trazas Distribuidas de Punta a Punta', 'https://videos.cloudnative.es/trazas-distribuidas-end-to-end', 'VIDEO', '2026-03-11T16:55:00Z'),
    ('Persistencia Event-Sourcing: Cuando y Cuando No', 'https://blog.cleancode.lat/event-sourcing-cuando', 'ARTICLE', '2026-03-14T08:20:00Z'),
    ('Documentando APIs con OpenAPI 4', 'https://academy.byteforge.dev/cursos/openapi-4-spring', 'COURSE', '2026-03-17T12:30:00Z'),
    ('Errores Comunes en Microservicios Java', 'https://podcast.javahoy.fm/episodios/93', 'PODCAST', '2026-03-20T18:25:00Z'),
    ('Indices y Rendimiento en PostgreSQL', 'https://blog.devnexus.io/postgresql-indices-rendimiento', 'ARTICLE', '2026-03-23T11:15:00Z'),
    ('Testing Contract-First con Spring Cloud', 'https://videos.cloudnative.es/contract-first-spring-cloud', 'VIDEO', '2026-03-26T15:10:00Z'),
    ('Autenticacion OAuth2 para BFF', 'https://academy.byteforge.dev/cursos/oauth2-bff-spring', 'COURSE', '2026-03-29T10:35:00Z'),
    ('Monitorizando Aplicaciones con Prometheus', 'https://blog.cleancode.lat/prometheus-spring-monitoring', 'ARTICLE', '2026-04-01T09:00:00Z'),
    ('Buenas Practicas de Logging Estructurado', 'https://videos.cloudnative.es/logging-estructurado-java', 'VIDEO', '2026-04-04T14:15:00Z'),
    ('Estrategias de Retry y Backoff', 'https://blog.devnexus.io/retry-backoff-estrategias', 'ARTICLE', '2026-04-07T17:05:00Z');

INSERT INTO subscriber (email) VALUES
    ('ana.garcia@northwind.io'),
    ('luis.martinez@globex.com'),
    ('maria.lopez@initech.co'),
    ('carlos.ramirez@umbrella.dev'),
    ('sofia.torres@starkindustries.com'),
    ('diego.fernandez@wayneenterprises.org'),
    ('valentina.ruiz@hooli.net'),
    ('jorge.castillo@acmecorp.io'),
    ('camila.mendoza@wonka.ai'),
    ('ricardo.vargas@vehement.tech'),
    ('paula.herrera@massive-dynamic.com'),
    ('andres.navarro@cyberdyne.systems'),
    ('laura.perez@oscorp.co'),
    ('gabriel.santos@soylent.green'),
    ('elena.rojas@aperturelabs.dev'),
    ('francisco.ortiz@vandalayindustries.com'),
    ('isabella.morales@blackmesa.org'),
    ('daniel.gomez@bluthcompany.net'),
    ('renata.silva@momcorp.biz'),
    ('tomas.aguirre@piedpiper.io'),
    ('ximena.reyes@dundermifflin.paper'),
    ('sebastian.leon@primatech.com'),
    ('natalia.romero@virtucon.co'),
    ('martin.vega@planetexpress.delivery'),
    ('julieta.castro@gencooliveoil.com');
